name: website
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y imagemagick sassc imagemagick

      # The pandoc version shipped with Ubuntu leads to broken codeblocks
      - run: wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
      - run: sudo dpkg -i pandoc-2.19.2-1-amd64.deb

      - run: make build
