name: website
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: website-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y imagemagick sassc imagemagick

      # The pandoc version shipped with Ubuntu leads to broken codeblocks
      - run: wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
      - run: sudo dpkg -i pandoc-2.19.2-1-amd64.deb

      - run: make build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/out
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
